### PR TITLE
Fixed negative transactions

### PR DESCRIPTION
**Pull request by JSKitty**
While messing around and testing the blockchain on my Naivecoin fork, I discovered it was possible to send "negative transactions", basically... you could 'steal' from any address, if you sent a minus transaction to them, even if that address didn't have those coins, or if the address didn't yet exist.

This means you could effectively create coins from thin air, just by adding a - onto the front of your transaction amount.

E.G: Sending -50 to bob --> bob loses 50 coins and you gain 50 coins. (Screenshot below will explain this visually, using the block-explorer)

image

This PR will fix this by looping through outputs of every regular transaction (Fee and Reward transactions are not checked), and if it encounters a negative output, the transaction is rejected. This is built into both Transaction.js and the miner index.

Hope this helps!! This is my first code commit to another project, take it easy on me! <3

### CODE REVIEW

**Comment by Chovanec** [comment]
I think empty transaction should not be rejected

**Comment by Chovanec** [comment]
And why you used decimal number in this condition:
`if (this.data.outputs[i].amount < 0.00000001) {`
this should work:
`if (this.data.outputs[i].amount < 0) {`
or this if you want reject even zero transaction:
`if (this.data.outputs[i].amount < 1) {`

**Comment by conradoqg** [comment]
Nice work @JSKitty! Thanks for this PR.

@Chovanec has a valid question. I think `<0` is good enough.

Changing that, I will approve this PR.

**Comment by JSKitty** [comment]
Fixed

**Pull request merged**
